[package]
name = "quadratic_voting"
version = "0.1.0"
edition = "2021"
author = "tara@parity.io"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num = "0.4.0"
time = "0.3.13"